# Generated by Django 5.1.6 on 2025-07-08 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_useraccount_porte_useraccount_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='cpf',
        ),
    ]
