# Generated by Django 5.1.6 on 2025-07-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0003_remove_pergunta_explicacao_dimensao_explicacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimensao',
            name='tipo',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='exclusao',
            field=models.CharField(choices=[('NENHUM', 'Nenhum'), ('MEI', 'Mei')], default='NENHUM', max_length=20),
        ),
    ]
