# Generated by Django 5.1.6 on 2025-07-08 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0004_remove_dimensao_tipo_pergunta_exclusao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='respostadimensao',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='respostamodulo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='respostadimensao',
            name='resposta_modulo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='questionario.respostamodulo'),
        ),
    ]
