# Generated by Django 5.1.6 on 2025-07-08 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionario", "0005_alter_respostadimensao_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="respostadimensao",
            name="resposta_modulo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="questionario.respostamodulo",
            ),
        ),
    ]
