# Generated by Django 5.1.6 on 2025-07-21 20:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0007_repostamoduloincompleta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RepostaModuloIncompleta',
            new_name='RespostaModuloIncompleta',
        ),
    ]
