# Generated by Django 5.1.6 on 2025-07-21 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0008_rename_repostamoduloincompleta_respostamoduloincompleta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respostamoduloincompleta',
            old_name='respotas',
            new_name='respostas',
        ),
    ]
